completed html-block-and-inline-Carolyne Golias
GCarolyne/c1024-code-solutions pull request #18
Opened 2024-10-29 19:13 UTC by GCarolyne

2024-10-30 15:41 UTC, shawnkost requested changes
Missing quiz questions, and don't forget to include screenshots in your pull request!

2024-10-30 15:41 UTC, shawnkost commented on html-block-and-inline/html-block-and-inline-quiz-notes.md
> +
Missing quiz questions!

2024-10-30 15:59 UTC, GCarolyne commented
<img width="626" alt="Screenshot 2024-10-30 at 8 59 33 AM" src="https://github.com/user-attachments/assets/e9815dc9-c608-4f0a-a805-f8ba806a1eb6">

2024-11-01 15:44 UTC, shawnkost approved these changes
👍🏻

2024-11-01 17:12 UTC, merged