completed html-lists-Carolyne Golias
GCarolyne/c1024-code-solutions pull request #19
Opened 2024-10-29 19:14 UTC by GCarolyne

2024-10-30 15:42 UTC, shawnkost requested changes
Missing a quiz question, and need to include a screenshot!

2024-10-30 15:42 UTC, shawnkost commented on html-lists/html-lists-quiz-notes.md
> +
Missing quiz question

2024-10-30 17:18 UTC, GCarolyne commented
<img width="284" alt="Screenshot 2024-10-30 at 10 18 27 AM" src="https://github.com/user-attachments/assets/b6db0627-3f85-4071-9a06-c6442976de7c">

2024-11-01 15:44 UTC, shawnkost approved these changes
👍🏻

2024-11-01 17:12 UTC, merged