Completed html-relative-links- Carolyne Golias
GCarolyne/c1024-code-solutions pull request #21
Opened 2024-10-29 21:08 UTC by GCarolyne

2024-10-30 15:43 UTC, shawnkost requested changes
One change, and missing a screenshot!

2024-10-30 15:43 UTC, shawnkost commented on html-relative-links/projects/projects.html
> +        <a href="../projects.html">Projects</a>
This should just be like this, because this file exist in the same directory, so we don't need to go up any levels

```suggestion
        <a href="projects.html">Projects</a>
```

2024-10-30 17:17 UTC, GCarolyne commented
<img width="383" alt="Screenshot 2024-10-30 at 10 16 54 AM" src="https://github.com/user-attachments/assets/
<img width="389" alt="Screenshot 2024-10-30 at 10 16 32 AM" src="https://github.com/user-attachments/assets/d13ff59d-daae-4118-b0a0-b21bdfafc5d1">
7be545cf-b705-413a-ad9f-2f5d59babf61">
<img width="362" alt="Screenshot 2024-10-30 at 10 16 40 AM" src="https://github.com/user-attachments/assets/5fc4ed0d-8a62-4857-a18c-dc4163b0af68">

<img width="363" alt="Screenshot 2024-10-30 at 10 16 48 AM" src="https://github.com/user-attachments/assets/a7667772-ed68-410c-9df5-c3c63dad2c7a">

2024-11-01 15:45 UTC, shawnkost approved these changes
👍🏻

2024-11-01 17:12 UTC, merged