completed typescript-forms-Carolyne Golias
GCarolyne/c1024-code-solutions pull request #41
Opened 2024-11-07 20:26 UTC by GCarolyne

![Screenshot 2024-11-07 at 12 14 25 PM](https://github.com/user-attachments/assets/4d1f50f1-102f-4a70-b70c-cbb0315931b1)
![Screenshot 2024-11-07 at 12 15 03 PM](https://github.com/user-attachments/assets/f1984827-93d6-49c8-99f3-2960955c429a)

2024-11-14 17:25 UTC, shawnkost requested changes
Just a few small changes here Carolyne!

2024-11-14 17:25 UTC, shawnkost commented on typescript-forms/form-events.ts
> +$input.addEventListener('focus', handleFocus);
`$input` should also get a `blur` event and an `input` event

2024-11-14 17:25 UTC, shawnkost commented on typescript-forms/form-events.ts
> +$input1.addEventListener('blur', handleBlur);
`$input1` should also get a `focus` event and an `input` event

2024-11-14 17:25 UTC, shawnkost commented on typescript-forms/form-events.ts
> +$textAr.addEventListener('input', handleInput);
`$textAr` should also get a `focus` event and an `blur` event

2024-11-18 18:10 UTC, GCarolyne commented
<img width="573" alt="Screenshot 2024-11-18 at 10 09 51 AM" src="https://github.com/user-attachments/assets/527d2f7f-1e95-4819-a627-5c613238c8a8">

2024-11-18 19:46 UTC, shawnkost approved these changes
👍🏻

2024-11-18 20:26 UTC, merged